---
- name: test if dnsmasq_port is set correctly
  assert:
    that:
      - dnsmasq_port is number
      - dnsmasq_port | int >= 0
      - dnsmasq_port | int <= 65536
    quiet: yes
  when:
    - dnsmasq_port is defined

- name: test if dnsmasq_domain_needed is set correctly
  assert:
    that:
      - dnsmasq_domain_needed is defined
      - dnsmasq_domain_needed is boolean
    quiet: yes

- name: test if dnsmasq_bogus_priv is set correctly
  assert:
    that:
      - dnsmasq_bogus_priv is defined
      - dnsmasq_bogus_priv is boolean
    quiet: yes

- name: test if dnsmasq_conf_file is set correctly
  assert:
    that:
      - dnsmasq_conf_file is defined
      - dnsmasq_conf_file | length > 0
    quiet: yes

- name: test if dnsmasq_dnssec is set correctly
  assert:
    that:
      - dnsmasq_dnssec is defined
      - dnsmasq_dnssec is boolean
    quiet: yes

- name: test if dnsmasq_dnssec_check_unsigned is set correctly
  assert:
    that:
      - dnsmasq_dnssec_check_unsigned is defined
      - dnsmasq_dnssec_check_unsigned is boolean
    quiet: yes

- name: test if dnsmasq_filterwin2k is set correctly
  assert:
    that:
      - dnsmasq_filterwin2k is defined
      - dnsmasq_filterwin2k is boolean
    quiet: yes

- name: test if dnsmasq_resolv_file is set correctly
  assert:
    that:
      - dnsmasq_resolv_file | length > 0
    quiet: yes
  when:
    - dnsmasq_resolv_file is defined

- name: test if dnsmasq_strict_order is set correctly
  assert:
    that:
      - dnsmasq_strict_order is defined
      - dnsmasq_strict_order is boolean
    quiet: yes

- name: test if dnsmasq_no_resolv is set correctly
  assert:
    that:
      - dnsmasq_no_resolv is defined
      - dnsmasq_no_resolv is boolean
    quiet: yes

- name: test if dnsmasq_no_poll is set correctly
  assert:
    that:
      - dnsmasq_no_poll is defined
      - dnsmasq_no_poll is boolean
    quiet: yes

- name: test if dnsmasq_servers is set correctly
  assert:
    that:
      - dnsmasq_servers | length > 0
      - dnsmasq_servers is iterable
    quiet: yes
  when:
    - dnsmasq_servers is defined

- name: test if item in dnsmasq_servers is set correctly
  assert:
    that:
      - item.domain is defined
      - item.domain | length > 0
      - item.nameserver is defined
      - item.nameserver | length > 0
    quiet: yes
  loop: "{{ dnsmasq_servers }}"
  when:
    - dnsmasq_servers is defined

- name: test if item.interface in dnsmasq_servers is set correctly
  assert:
    that:
      - item.interface | length > 0
    quiet: yes
  loop: "{{ dnsmasq_servers }}"
  when:
    - dnsmasq_servers is defined
    - item.interface is defined

- name: test if item.port in dnsmasq_servers is set correctly
  assert:
    that:
      - item.port is number
      - item.port | int >= 0
      - item.port | int <= 65536
    quiet: yes
  loop: "{{ dnsmasq_servers }}"
  when:
    - dnsmasq_servers is defined
    - item.port is defined

- name: test if dnsmasq_locals is set correctly
  assert:
    that:
      - dnsmasq_locals | length > 0
      - dnsmasq_locals is iterable
    quiet: yes
  when:
    - dnsmasq_locals is defined

- name: test if item.domain in dnsmasq_locals is set correctly
  assert:
    that:
      - item.domain is defined
      - item.domain | length > 0
    quiet: yes
  when:
    - dnsmasq_locals is defined

- name: test if dnsmasq_addresses is set correctly
  assert:
    that:
      - dnsmasq_addresses | length > 0
      - dnsmasq_addresses is iterable
    quiet: yes
  when:
    - dnsmasq_addresses is defined

- name: test if item in dnsmasq_addresses is set correctly
  assert:
    that:
      - item.domain is defined
      - item.domain | length > 0
      - item.address is defined
      - item.address | length > 0
    quiet: yes
  loop: "{{ dnsmasq_addresses }}"
  when:
    - dnsmasq_addresses is defined

- name: test if dnsmasq_ipsets is set correctly
  assert:
    that:
      - dnsmasq_ipsets | length > 0
      - dnsmasq_ipsets is iterable
    quiet: yes
  when:
    - dnsmasq_ipsets is defined

- name: test if item in dnsmasq_ipsets is set correctly
  assert:
    that:
      - item.domains is defined
      - item.domains | length > 0
      - item.domains is iterable
      - item.destination is defined
      - item.destination | length > 0
      - item.option is defined
      - item.option | length > 0
    quiet: yes
  loop: "{{ dnsmasq_ipsets }}"
  when:
    - dnsmasq_ipsets is defined

- name: test if dnsmasq_interfaces is set correctly
  assert:
    that:
      - dnsmasq_interfaces | length > 0
      - dnsmasq_interfaces is iterable
    quiet: yes
  when:
    - dnsmasq_interfaces is defined

- name: test if item in dnsmasq_interfaces is set correctly
  assert:
    that:
      - item.name is defined
      - item.name | length > 0
    quiet: yes
  loop: "{{ dnsmasq_interfaces }}"
  when:
    - dnsmasq_interfaces is defined

- name: test if dnsmasq_except_interface is set correctly
  assert:
    that:
      - dnsmasq_except_interface | length > 0
    quiet: yes
  when:
    - dnsmasq_except_interface is defined

- name: test if dnsmasq_listen_addresses is set correctly
  assert:
    that:
      - dnsmasq_listen_addresses | length > 0
      - dnsmasq_listen_addresses is iterable
    quiet: yes
  when:
    - dnsmasq_listen_addresses is defined

- name: test if item in dnsmasq_listen_addresses is set correctly
  assert:
    that:
      - item.name is defined
      - item.name | length > 0
    quiet: yes
  loop: "{{ dnsmasq_listen_addresses }}"
  when:
    - dnsmasq_listen_addresses is defined

- name: test if dnsmasq_no_dhcp_interface is set correctly
  assert:
    that:
      - dnsmasq_no_dhcp_interface is defined
    quiet: yes

- name: test if dnsmasq_local_service is set correctly
  assert:
    that:
      - dnsmasq_local_service is defined
      - dnsmasq_local_service is boolean
    quiet: yes

- name: test if dnsmasq_bind_interfaces is set correctly
  assert:
    that:
      - dnsmasq_bind_interfaces is defined
      - dnsmasq_bind_interfaces is boolean
    quiet: yes

- name: test if dnsmasq_no_hosts is set correctly
  assert:
    that:
      - dnsmasq_no_hosts is defined
      - dnsmasq_no_hosts is boolean
    quiet: yes

- name: test if dnsmasq_addn_hosts is set correctly
  assert:
    that:
      - dnsmasq_addn_hosts | length > 0
    quiet: yes
  when:
    - dnsmasq_addn_hosts is defined

- name: test if dnsmasq_expand_hosts is set correctly
  assert:
    that:
      - dnsmasq_expand_hosts is defined
      - dnsmasq_expand_hosts is boolean
    quiet: yes

- name: test if dnsmasq_domains is set correctly
  assert:
    that:
      - dnsmasq_domains | length > 0
      - dnsmasq_domains is iterable
    quiet: yes
  when:
    - dnsmasq_domains is defined

- name: test if item.name in dnsmasq_domains is set correctly
  assert:
    that:
      - item.name is defined
      - item.name | length > 0
    quiet: yes
  loop: "{{ dnsmasq_domains }}"
  when:
    - dnsmasq_domains is defined

- name: test if item.subnet in dnsmasq_domains is set correctly
  assert:
    that:
      - item.subnet | length > 0
    quiet: yes
  loop: "{{ dnsmasq_domains }}"
  when:
    - dnsmasq_domains is defined
    - item.subnet is defined

- name: test if item.from in dnsmasq_domains is set correctly
  assert:
    that:
      - item.from | length > 0
    quiet: yes
  loop: "{{ dnsmasq_domains }}"
  when:
    - dnsmasq_domains is defined
    - item.from is defined

- name: test if item.until in dnsmasq_domains is set correctly
  assert:
    that:
      - item.until | length > 0
    quiet: yes
  loop: "{{ dnsmasq_domains }}"
  when:
    - dnsmasq_domains is defined
    - item.until is defined

- name: test if dnsmasq_dhcp_ranges is set correctly
  assert:
    that:
      - dnsmasq_dhcp_ranges | length > 0
      - dnsmasq_dhcp_ranges is iterable
    quiet: yes
  when:
    - dnsmasq_dhcp_ranges is defined

- name: test if item.from in dnsmasq_dhcp_ranges  is set correctly
  assert:
    that:
      - item.from is defined
      - item.from | length > 0
    quiet: yes
  when:
    - dnsmasq_dhcp_ranges is defined
  loop: "{{ dnsmasq_dhcp_ranges }}"

- name: test if item.until in dnsmasq_dhcp_ranges  is set correctly
  assert:
    that:
      - item.until | length > 0
    quiet: yes
  when:
    - dnsmasq_dhcp_ranges is defined
    - item.until is defined
  loop: "{{ dnsmasq_dhcp_ranges }}"

- name: test if item.leasetime in dnsmasq_dhcp_ranges  is set correctly
  assert:
    that:
      - item.leasetime | length > 0
    quiet: yes
  when:
    - dnsmasq_dhcp_ranges is defined
    - item.leasetime is defined
  loop: "{{ dnsmasq_dhcp_ranges }}"

- name: test if item.subnet in dnsmasq_dhcp_ranges  is set correctly
  assert:
    that:
      - item.subnet | length > 0
    quiet: yes
  when:
    - dnsmasq_dhcp_ranges is defined
    - item.subnet is defined
  loop: "{{ dnsmasq_dhcp_ranges }}"

- name: test if item.sets in dnsmasq_dhcp_ranges  is set correctly
  assert:
    that:
      - item.sets | length > 0
      - item.sets is iterabel
    quiet: yes
  when:
    - dnsmasq_dhcp_ranges is defined
    - item.sets is defined
  loop: "{{ dnsmasq_dhcp_ranges }}"

- name: test if item.tags in dnsmasq_dhcp_ranges  is set correctly
  assert:
    that:
      - item.tags | length > 0
      - item.tags is iterable
    quiet: yes
  when:
    - dnsmasq_dhcp_ranges is defined
    - item.tags is defined
  loop: "{{ dnsmasq_dhcp_ranges }}"

- name: test if item.options in dnsmasq_dhcp_ranges  is set correctly
  assert:
    that:
      - item.options | length > 0
      - item.options is iterable
    quiet: yes
  when:
    - dnsmasq_dhcp_ranges is defined
    - item.options is defined
  loop: "{{ dnsmasq_dhcp_ranges }}"

- name: test if dnsmasq_enable_ra is set correctly
  assert:
    that:
      - dnsmasq_enable_ra is defined
      - dnsmasq_enable_ra is boolean
    quiet: yes

- name: test if dnsmasq_hosts is set correctly
  assert:
    that:
      - dnsmasq_hosts | length > 0
      - dnsmasq_hosts is iterable
    quiet: yes
  when:
    - dnsmasq_hosts is defined

- name: test if items in dnsmasq_hosts are set correctly
  assert:
    that:
      - item.name is defined
      - item.name | length > 0
      - item.value is defined
      - item.value | length > 0
    quiet: yes
  loop: "{{ dnsmasq_hosts }}"
  when:
    - dnsmasq_hosts is defined

- name: test if dnsmasq_dhcp_ignore is set correctly
  assert:
    that:
      - dnsmasq_dhcp_ignore | length > 0
    quiet: yes
  when:
    - dnsmasq_dhcp_ignore is defined

- name: test if dnsmasq_dhcp_vendorclass is set correctly
  assert:
    that:
      - dnsmasq_dhcp_vendorclass | length > 0
    quiet: yes
  when:
    - dnsmasq_dhcp_vendorclass is defined

- name: test if dnsmasq_dhcp_userclass is set correctly
  assert:
    that:
      - dnsmasq_dhcp_userclass | length > 0
    quiet: yes
  when:
    - dnsmasq_dhcp_userclass is defined

- name: test if dnsmasq_dhcp_mac is set correctly
  assert:
    that:
      - dnsmasq_dhcp_mac | length > 0
    quiet: yes
  when:
    - dnsmasq_dhcp_mac is defined

- name: test if dnsmasq_read_ethers is set correctly
  assert:
    that:
      - dnsmasq_read_ethers is defined
      - dnsmasq_read_ethers is boolean
    quiet: yes

- name: test if dnsmasq_dhcp_options is set correctly
  assert:
    that:
      - dnsmasq_dhcp_options | length > 0
      - dnsmasq_dhcp_options is iterable
    quiet: yes
  when:
    - dnsmasq_dhcp_options is defined

- name: test if items in dnsmasq_dhcp_options are set correctly
  assert:
    that:
      - item.name is defined
      - item.name | length > 0
      - item.value is defined
      - item.value | length > 0
    quiet: yes
  loop: "{{ dnsmasq_dhcp_options }}"
  when:
    - dnsmasq_dhcp_options is defined

- name: test if dnsmasq_dhcp_option_force is set correctly
  assert:
    that:
      - dnsmasq_dhcp_option_force | length > 0
      - dnsmasq_dhcp_option_force is iterable
    quiet: yes
  when:
    - dnsmasq_dhcp_option_force is defined

- name: test if items in dnsmasq_dhcp_option_force are set correctly
  assert:
    that:
      - item.name is defined
      - item.name | length > 0
      - item.value is defined
      - item.value | length > 0
    quiet: yes
  loop: "{{ dnsmasq_dhcp_option_force }}"
  when:
    - dnsmasq_dhcp_option_force is defined

- name: test if dnsmasq_dhcp_boot is set correctly
  assert:
    that:
      - dnsmasq_dhcp_boot | length > 0
    quiet: yes
  when:
    - dnsmasq_dhcp_boot is defined

- name: test if dnsmasq_enable_tftp is set correctly
  assert:
    that:
      - dnsmasq_enable_tftp is defined
      - dnsmasq_enable_tftp is boolean
    quiet: yes

- name: test if dnsmasq_tftp_root is set correctly
  assert:
    that:
      - dnsmasq_tftp_root | length > 0
    quiet: yes
  when:
    - dnsmasq_tftp_root is defined

- name: test if dnsmasq_tftp_no_fail is set correctly
  assert:
    that:
      - dnsmasq_tftp_no_fail is defined
      - dnsmasq_tftp_no_fail is boolean
    quiet: yes

- name: test if dnsmasq_tftp_secure is set correctly
  assert:
    that:
      - dnsmasq_tftp_secure is defined
      - dnsmasq_tftp_secure is boolean
    quiet: yes

- name: test if dnsmasq_tftp_no_blocksize is set correctly
  assert:
    that:
      - dnsmasq_tftp_no_blocksize is defined
      - dnsmasq_tftp_no_blocksize is boolean
    quiet: yes

- name: test if dnsmasq_dhcp_lease_max is set correctly
  assert:
    that:
      - dnsmasq_dhcp_lease_max is number
      - dnsmasq_dhcp_lease_max | int >= 0
    quiet: yes
  when:
    - dnsmasq_dhcp_lease_max is defined

- name: test if dnsmasq_dhcp_leasefile is set correctly
  assert:
    that:
      - dnsmasq_dhcp_leasefile | length > 0
    quiet: yes
  when:
    - dnsmasq_dhcp_leasefile is defined

- name: test if dnsmasq_dhcp_authoritative is set correctly
  assert:
    that:
      - dnsmasq_dhcp_authoritative is defined
      - dnsmasq_dhcp_authoritative is boolean
    quiet: yes

- name: test if dnsmasq_dhcp_rapid_commit is set correctly
  assert:
    that:
      - dnsmasq_dhcp_rapid_commit is defined
      - dnsmasq_dhcp_rapid_commit is boolean
    quiet: yes

- name: test if dnsmasq_dhcp_script is set correctly
  assert:
    that:
      - dnsmasq_dhcp_script is defined
      - dnsmasq_dhcp_script | length > 0
    quiet: yes

- name: test if dnsmasq_cache_size is set correctly
  assert:
    that:
      - dnsmasq_cache_size is number
      - dnsmasq_cache_size | int >= 0
    quiet: yes
  when:
    - dnsmasq_cache_size is defined

- name: test if dnsmasq_no_negcache is set correctly
  assert:
    that:
      - dnsmasq_no_negcache is defined
      - dnsmasq_no_negcache is boolean
    quiet: yes

- name: test if dnsmasq_local_ttl is set correctly
  assert:
    that:
      - dnsmasq_local_ttl is number
      - dnsmasq_local_ttl | int >= 0
    quiet: yes
  when:
    - dnsmasq_local_ttl is defined

- name: test if dnsmasq_bogus_nxdomain is set correctly
  assert:
    that:
      - dnsmasq_bogus_nxdomain | length > 0
    quiet: yes
  when:
    - dnsmasq_bogus_nxdomain is defined

- name: test if dnsmasq_aliases is set correctly
  assert:
    that:
      - dnsmasq_aliases | length > 0
      - dnsmasq_aliases is iterable
    quiet: yes
  when:
    - dnsmasq_aliases is defined

- name: test if items in dnsmasq_aliases are set correctly
  assert:
    that:
      - item.from is defined
      - item.from | length > 0
      - item.until is defined
      - item.until | length > 0
    quiet: yes
  loop: "{{ dnsmasq_aliases }}"
  when:
    - dnsmasq_aliases is defined

- name: test if item.subnet in dnsmasq_aliases is set correctly
  assert:
    that:
      - item.subnet | length > 0
    quiet: yes
  loop: "{{ dnsmasq_aliases }}"
  when:
    - dnsmasq_aliases is defined
    - item.subnet is defined

- name: test if dnsmasq_mx_hosts is set correctly
  assert:
    that:
      - dnsmasq_mx_hosts | length > 0
      - dnsmasq_mx_hosts is iterable
    quiet: yes
  when:
    - dnsmasq_mx_hosts is defined

- name: test if item.domain in dnsmasq_mx_hosts is set correctly
  assert:
    that:
      - item.domain is defined
      - item.domain | length > 0
    quiet: yes
  loop: "{{ dnsmasq_mx_hosts }}"
  when:
    - dnsmasq_mx_hosts is defined

- name: test if item.host in dnsmasq_mx_hosts is set correctly
  assert:
    that:
      - item.host | length > 0
    quiet: yes
  loop: "{{ dnsmasq_mx_hosts }}"
  when:
    - dnsmasq_mx_hosts is defined
    - item.host is defined

- name: test if item.prority in dnsmasq_mx_hosts is set correctly
  assert:
    that:
      - item.prority | length > 0
    quiet: yes
  loop: "{{ dnsmasq_mx_hosts }}"
  when:
    - dnsmasq_mx_hosts is defined
    - item.prority is defined

- name: test if dnsmasq_localmx is set correctly
  assert:
    that:
      - dnsmasq_localmx is defined
      - dnsmasq_localmx is boolean
    quiet: yes

- name: test if dnsmasq_selfmx is set correctly
  assert:
    that:
      - dnsmasq_selfmx is defined
      - dnsmasq_selfmx is boolean
    quiet: yes

- name: test if dnsmasq_src_hosts is set correctly
  assert:
    that:
      - dnsmasq_src_hosts | length > 0
      - dnsmasq_src_hosts is iterable
    quiet: yes
  when:
    - dnsmasq_src_hosts is defined

- name: test if items in dnsmasq_src_hosts are set correctly
  assert:
    that:
      - item.record is defined
      - item.record | length > 0
      - item.destinatio is defined
      - item.destinatio | length > 0
      - item.port is defined
      - item.port | length > 0
      - item.port is number
    quiet: yes
  loop: "{{ dnsmasq_src_hosts }}"
  when:
    - dnsmasq_src_hosts is defined

- name: test if item.priority in dnsmasq_src_hosts is set correctly
  assert:
    that:
      - item.priority is number
      - item.priority | int >= 0
    quiet: yes
  when:
    - dnsmasq_src_hosts is defined
    - item.priority is defined

- name: test if dnsmasq_log_queries is set correctly
  assert:
    that:
      - dnsmasq_log_queries is defined
      - dnsmasq_log_queries is boolean
    quiet: yes

- name: test if dnsmasq_log_dhcp is set correctly
  assert:
    that:
      - dnsmasq_log_dhcp is defined
      - dnsmasq_log_dhcp is boolean
    quiet: yes

- name: test if dnsmasq_conf_dir is set correctly
  assert:
    that:
      - dnsmasq_conf_dir | length > 0
    quiet: yes
  when:
    - dnsmasq_conf_dir is defined

- name: test if dnsmasq_dhcp_name_match is set correctly
  assert:
    that:
      - dnsmasq_dhcp_name_match | length > 0
    quiet: yes
  when:
    - dnsmasq_dhcp_name_match is defined

- name: test if dnsmasq_ignore_names is set correctly
  assert:
    that:
      - dnsmasq_ignore_names | length > 0
    quiet: yes
  when:
    - dnsmasq_ignore_names is defined
